### PR TITLE
Remove `@matrixai/quic` and `@matrixai/id` and separate error tree

### PR DESCRIPTION
**Pull request by CMCDragonkai**
### Description

Clean up after extraction.

### Tasks

- [x] 1. `@matrixai/quic` configuration should be encapsulated by the PK library, PK CLI should not have any knowledge about QUIC
- [x] 2. The `@matrixai/id` can be replaced by the new node ID utils `encodeNodeIdString`, `decodeNodeIdString` and `createNodeIdGenerator`.
- [x] 3. The error tree under `Polykey-CLI` should be separate. It should not be extending the library. It is its own thing. I believe it can be organised under `ErrorPolykeyCLI`.
  - And the naming of the errors should probably be simplified, with either a plain prefix of the relevant domains or just a suffix. I think in the case of CLI, a plain suffix is fine. Like `ErrorPolykeyCLI...`

### Final checklist

* ~Domain specific tests~
* ~Full tests~
* [x] Updated inline-comment documentation
* [x] Lint fixed
* [x] Squash and rebased
* [x] Sanity check the final build

### CODE REVIEW

**Comment by CMCDragonkai** [comment]
Tasks 1. and 2. are waiting on the next prerelease @tegefaulkes.

**Comment by CMCDragonkai** [comment]
Task 1. is pending an alignment of the `src/config.ts`.

**Comment by tegefaulkes** [comment]
Ok so I've fixed  up the config usage and how agent is started. But this is not really testable until Polykey is in a fully working state. 

What is the scope of this PR? I've done task 1 now but the tests will still be broken.

**Comment by CMCDragonkai** [comment]
The scope is whatever is necessary to get it into staging. Then just squash merge. Testing can be done on staging.

**Comment by tegefaulkes** [comment]
It should be good then. Just need to squash and merge.

**Comment by tegefaulkes** [comment]
This is done now. Tests still need to be fixed but with `Polykey` in an unstable state it would be hard to tell if it's a `CLi` or `Polykey` problem right now.

We'll be fixing tests in the staging branch or a separate PR.

**Pull request merged**
