### PR TITLE
Refactor NixOS modules and implement `home-manager` modules

### PR DESCRIPTION
**Pull request by brynblack**
### Description

This PR updates the existing NixOS modules configuration to remove `programs.polykey` from the global user-space, and instead isolate it into a per-user based configuration utilising `home-manager`. 

### Tasks
- [x] 1. Remove `programs.polykey` NixOS module
- [x] 2. Add home-manager module for user-level service

### Final checklist

* [x] Domain specific tests
* [x] Full tests
* [x] Updated inline-comment documentation
* [x] Lint fixed
* [x] Squash and rebased
* [x] Sanity check the final build

### CODE REVIEW

**Comment by CMCDragonkai** [comment]
We still need the regular system module.

**Comment by CMCDragonkai** [comment]
Also make sure to follow and reference the new flake output schema.

**Comment by CMCDragonkai** [comment]
In your PR spec, you should be removing all the comments `<!-- --->`

**Comment by CMCDragonkai** [comment]
The CI still needs to be updated with the system registries (that needs to be done on both https://github.com/MatrixAI/nixpkgs-matrix-private and Orchestrator) and then task 3. can only be done after this is merged, because you will get the commit revision and update the overlay.

**Comment by brynblack** [comment]
I've merged it as it seems all good.

**Pull request merged**
