### PR TITLE
Indirect package set flake input

### PR DESCRIPTION
**Pull request by brynblack**
### Description

This PR incorporates the new indirect flake input system.

### Tasks

- [x] 1. Update `flake.nix` to use indirect inputs
- [x] 2. Remove `-dirty` from revision string

### Final checklist

* [x] Domain specific tests
* [x] Full tests
* [x] Updated inline-comment documentation
* [x] Lint fixed
* [x] Squash and rebased
* [x] Sanity check the final build

### CODE REVIEW

**Comment by CMCDragonkai** [comment]
What's blocking this from merge?

**Comment by CMCDragonkai** [comment]
Hey @brynblack don't do tag releases from branches. They are only allowed from staging branch.

**Comment by CMCDragonkai** [comment]
It might even break something.

@tegefaulkes please check that this works.

**Comment by tegefaulkes** [comment]
We went over it already. It's already fixed and I explained the problem.

**Pull request merged**
